// Copyright 2024 Craftsoft LLC. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v25.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace build_info_windows {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class BuildInfoHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



// Generated class from Pigeon that represents data sent in messages.
class BuildInfoDataPigeon {
 public:
  // Constructs an object setting all non-nullable fields.
  BuildInfoDataPigeon();

  // Constructs an object setting all fields.
  explicit BuildInfoDataPigeon(
    const int64_t* build_date,
    const int64_t* install_date);

  const int64_t* build_date() const;
  void set_build_date(const int64_t* value_arg);
  void set_build_date(int64_t value_arg);

  const int64_t* install_date() const;
  void set_install_date(const int64_t* value_arg);
  void set_install_date(int64_t value_arg);

 private:
  static BuildInfoDataPigeon FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class BuildInfoHostApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<int64_t> build_date_;
  std::optional<int64_t> install_date_;
};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;
 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class BuildInfoHostApi {
 public:
  BuildInfoHostApi(const BuildInfoHostApi&) = delete;
  BuildInfoHostApi& operator=(const BuildInfoHostApi&) = delete;
  virtual ~BuildInfoHostApi() {}
  virtual ErrorOr<BuildInfoDataPigeon> FromPlatform() = 0;

  // The codec used by BuildInfoHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `BuildInfoHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    BuildInfoHostApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    BuildInfoHostApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  BuildInfoHostApi() = default;
};
}  // namespace build_info_windows
#endif  // PIGEON_MESSAGES_G_H_
