name: build_info
description: "Flutter plugin that retrieves build date and time and installation date and time."
repository: https://github.com/craftsoft-dev/flutter_build_info/tree/main/build_info
issue_tracker: https://github.com/craftsoft-dev/flutter_build_info/issues
version: 1.1.0
homepage: https://github.com/craftsoft-dev/flutter_build_info

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

flutter:
  plugin:
    platforms:
      android:
        default_package: build_info_android
      ios:
        default_package: build_info_ios
      linux:
        default_package: build_info_linux
      macos:
        default_package: build_info_macos
      web:
        default_package: build_info_web
      windows:
        default_package: build_info_windows

dependencies:
  flutter:
    sdk: flutter
  
  build_info_android: ^1.1.0
  build_info_ios: ^1.1.0
  build_info_linux: ^1.1.0
  build_info_macos: ^1.1.0
  build_info_platform_interface: ^1.1.0
  build_info_web: ^1.1.0
  build_info_windows: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  plugin_platform_interface: ^2.1.8
