name: build_info_ios
description: "iOS implementation of Flutter plugin that retrieves build date and time and installation date and time."
repository: https://github.com/craftsoft-dev/flutter_build_info/tree/main/build_info_ios
issue_tracker: https://github.com/craftsoft-dev/flutter_build_info/issues
version: 1.1.0
homepage: https://github.com/craftsoft-dev/flutter_build_info

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

flutter:
  plugin:
    implements: build_info
    platforms:
      ios:
        pluginClass: BuildInfoPlugin
        fileName: build_info_ios.dart
        dartPluginClass: BuildInfoIOS

dependencies:
  flutter:
    sdk: flutter
  build_info_platform_interface: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^25.1.0
  plugin_platform_interface: ^2.1.8
  flutter_lints: ^5.0.0
