name: build_info_platform_interface
description: "A common platform interface for the build_info plugin."
repository: https://github.com/craftsoft-dev/flutter_build_info
issue_tracker: https://github.com/craftsoft-dev/flutter_build_info/issues
version: 1.0.0
homepage: https://github.com/craftsoft-dev/flutter_build_info

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
