name: build_info_platform_interface
description: "Common platform interface for the build_info plugin to retrieves build date and time and installation date and time."
repository: https://github.com/craftsoft-dev/flutter_build_info/tree/main/build_info_platform_interface
issue_tracker: https://github.com/craftsoft-dev/flutter_build_info/issues
version: 1.1.0
homepage: https://github.com/craftsoft-dev/flutter_build_info

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
