// Copyright 2024 Craftsoft LLC. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v16.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct BuildInfoDataPigeon {
  var buildDate: Int64? = nil
  var installDate: Int64? = nil

  static func fromList(_ list: [Any?]) -> BuildInfoDataPigeon? {
    let buildDate: Int64? = isNullish(list[0]) ? nil : (list[0] is Int64? ? list[0] as! Int64? : Int64(list[0] as! Int32))
    let installDate: Int64? = isNullish(list[1]) ? nil : (list[1] is Int64? ? list[1] as! Int64? : Int64(list[1] as! Int32))

    return BuildInfoDataPigeon(
      buildDate: buildDate,
      installDate: installDate
    )
  }
  func toList() -> [Any?] {
    return [
      buildDate,
      installDate,
    ]
  }
}
private class BuildInfoHostApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return BuildInfoDataPigeon.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class BuildInfoHostApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BuildInfoDataPigeon {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class BuildInfoHostApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return BuildInfoHostApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return BuildInfoHostApiCodecWriter(data: data)
  }
}

class BuildInfoHostApiCodec: FlutterStandardMessageCodec {
  static let shared = BuildInfoHostApiCodec(readerWriter: BuildInfoHostApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BuildInfoHostApi {
  func fromPlatform() throws -> BuildInfoDataPigeon
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BuildInfoHostApiSetup {
  /// The codec used by BuildInfoHostApi.
  static var codec: FlutterStandardMessageCodec { BuildInfoHostApiCodec.shared }
  /// Sets up an instance of `BuildInfoHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BuildInfoHostApi?) {
    let fromPlatformChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.build_info_ios.BuildInfoHostApi.fromPlatform", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fromPlatformChannel.setMessageHandler { _, reply in
        do {
          let result = try api.fromPlatform()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      fromPlatformChannel.setMessageHandler(nil)
    }
  }
}
