name: build_info_example
description: "Demonstrates how to use the build_info plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  build_info:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

#dependency_overrides:
#  build_info_android:
#    path: ../../build_info_android
#  build_info_ios:
#    path: ../../build_info_ios
#  build_info_linux:
#    path: ../../build_info_linux
#  build_info_macos:
#    path: ../../build_info_macos
#  build_info_windows:
#    path: ../../build_info_windows
